spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdfolio?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rlatnehd@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

oauth2:
  user:
    github:
      client-id: 11111
      client-secret: 11111
      redirect-uri: 11111
      access-token-uri: 11111
      user-info-uri: 11111
    kakao:
      client-id: 11111
      client-secret: 11111
      redirect-uri: 11111
      access-token-uri: 11111
      user-info-uri: 11111
    google:
      client-id: 11111
      client-secret: 11111
      redirect-uri: 11111
      access-token-uri: 11111
      user-info-uri: 11111
jwt:
  secret: 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111